language: node_js

sudo: false

# track upstream node_js matrix:
# - https://github.com/hexojs/hexo/blob/master/.travis.yml
# - https://github.com/sass/node-sass/blob/master/.travis.yml
node_js:
  - node # Current stable
  - lts/* # Most recent LTS version
  - 10 # Explicitly include an active LTS version

script:
  - npm run lint
  - npm run test

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
